[project]
name = "agent-hr-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-core>=0.1.52,<0.2.0",
    "langchain>=0.1.20,<0.2.0",
    "langchain-community>=0.0.38,<0.1.0",
    "langchain-openai",
    "langchain-google-genai",
    "google-api-python-client",
    "google-auth-httplib2",
    "google-auth-oauthlib",
    "faiss-cpu",
    "duckduckgo-search",
    "mcp[cli]",
    "boto3",
    "botocore",
    "langchain-aws",
    "pypdf",
    "python-dotenv",
    "langfuse",
    "tenacity",
    "typing-extensions",
    "pydantic>=2.0.0",
    "nemoguardrails[all]",
    "anthropic"
]
[tool.setuptools.packages.find]
exclude = ["hr_docs*", "faiss_index*"]
